package frc.robot;

/**
 * Application-wide constants.
 * Hardware-specific swerve constants are in TunerConstants (generated by Tuner X).
 */
public class Constants {

    /**
     * Operator interface configuration.
     */
    public static final class OperatorConstants {
        /** USB port for driver Xbox controller */
        public static final int DRIVER_CONTROLLER_PORT = 0;
    }

    /**
     * Drivetrain control constants.
     */
    public static final class DriveConstants {
        /** Maximum angular rate in rotations per second */
        public static final double MAX_ANGULAR_RATE = 0.75;

        /** Slew rate limit for acceleration (units per second) */
        public static final double SLEW_RATE_LIMIT = 3.0;

        /** Deadband percentage for joystick inputs */
        public static final double DEADBAND_PERCENT = 0.1;
    }
}
